export const rows = [
    { id: 1, name: "John Doe", age: 30, email: "john@example.com" },
    { id: 2, name: "Jane Smith", age: 25, email: "jane@example.com" },
    { id: 3, name: "Bob Johnson", age: 35, email: "bob@example.com" },
    { id: 4, name: "Donald trump", age: 45, email: "trump@example.com" },
    { id: 5, name: "Joe biden", age: 15, email: "joe@example.com" },
    { id: 6, name: "Harry jane", age: 10, email: "harry@example.com" },
    { id: 7, name: "Rishi sunak", age: 5, email: "sunak@example.com" },
    { id: 8, name: "Narendra modi", age: 55, email: "modi@example.com" },
    { id: 9, name: "White house", age: 65, email: "white@example.com" },
    { id: 10, name: "Parliament", age: 75, email: "pal@example.com" },
    { id: 11, name: "New York", age: 85, email: "york@example.com" },
    { id: 12, name: "Vatican city", age: 95, email: "city@example.com" },
    { id: 13, name: "Hong kong", age: 20, email: "hong@example.com" },
  ];